header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: short_camera
height: 720
width: 1280
distortion_model: plumb_bob
D: [-0.456674, 0.209842, 0.002991, 0.001288, 0.000000]
K: [ 1309.67969,     0.     ,   655.45161,
             0.     ,  1311.74663,   357.79608,
             0.     ,     0.     ,     1.     ]
R: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
P: [ 1150.4386 ,     0.     ,   662.07592,     0.     ,
             0.     ,  1264.92883,   358.65462,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

