header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: short_camera
height: 720
width: 1280
distortion_model: plumb_bob
D: [0.44800, 0.68300, 0.01200, 0.00200, -0.41200]
K: [ 1095.00000,     0.     ,   644.00000,
             0.     ,  606.00000,   375.00000,
             0.     ,     0.     ,     1.     ]
R: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
P: [ 1422.49451 ,     0.     ,   644.82337,     0.     ,
             0.     ,  785.15155,   377.25190,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
